name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.4.1.app
      
    - name: Build and Test
      run: xcodebuild clean build test -workspace Simple-Addition-Task.xcodeproj -scheme "Simple-Addition-Task" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
